/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PinRouteImport } from './routes/pin'
import { Route as CortexRouteImport } from './routes/cortex'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ApiPinRouteImport } from './routes/api/pin'
import { Route as ApiJarvisRouteImport } from './routes/api/jarvis'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiProposalsIdRouteImport } from './routes/api/proposals.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PinRoute = PinRouteImport.update({
  id: '/pin',
  path: '/pin',
  getParentRoute: () => rootRouteImport,
} as any)
const CortexRoute = CortexRouteImport.update({
  id: '/cortex',
  path: '/cortex',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPinRoute = ApiPinRouteImport.update({
  id: '/api/pin',
  path: '/api/pin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJarvisRoute = ApiJarvisRouteImport.update({
  id: '/api/jarvis',
  path: '/api/jarvis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProposalsIdRoute = ApiProposalsIdRouteImport.update({
  id: '/api/proposals/$id',
  path: '/api/proposals/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/calendar': typeof CalendarRoute
  '/cortex': typeof CortexRoute
  '/pin': typeof PinRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/events': typeof ApiEventsRoute
  '/api/jarvis': typeof ApiJarvisRoute
  '/api/pin': typeof ApiPinRoute
  '/api/proposals/$id': typeof ApiProposalsIdRoute
}
export interface FileRoutesByTo {
  '/calendar': typeof CalendarRoute
  '/cortex': typeof CortexRoute
  '/pin': typeof PinRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/events': typeof ApiEventsRoute
  '/api/jarvis': typeof ApiJarvisRoute
  '/api/pin': typeof ApiPinRoute
  '/api/proposals/$id': typeof ApiProposalsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/calendar': typeof CalendarRoute
  '/cortex': typeof CortexRoute
  '/pin': typeof PinRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/events': typeof ApiEventsRoute
  '/api/jarvis': typeof ApiJarvisRoute
  '/api/pin': typeof ApiPinRoute
  '/api/proposals/$id': typeof ApiProposalsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/calendar'
    | '/cortex'
    | '/pin'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/events'
    | '/api/jarvis'
    | '/api/pin'
    | '/api/proposals/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/calendar'
    | '/cortex'
    | '/pin'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/events'
    | '/api/jarvis'
    | '/api/pin'
    | '/api/proposals/$id'
  id:
    | '__root__'
    | '/calendar'
    | '/cortex'
    | '/pin'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/events'
    | '/api/jarvis'
    | '/api/pin'
    | '/api/proposals/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CalendarRoute: typeof CalendarRoute
  CortexRoute: typeof CortexRoute
  PinRoute: typeof PinRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiJarvisRoute: typeof ApiJarvisRoute
  ApiPinRoute: typeof ApiPinRoute
  ApiProposalsIdRoute: typeof ApiProposalsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pin': {
      id: '/pin'
      path: '/pin'
      fullPath: '/pin'
      preLoaderRoute: typeof PinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cortex': {
      id: '/cortex'
      path: '/cortex'
      fullPath: '/cortex'
      preLoaderRoute: typeof CortexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pin': {
      id: '/api/pin'
      path: '/api/pin'
      fullPath: '/api/pin'
      preLoaderRoute: typeof ApiPinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jarvis': {
      id: '/api/jarvis'
      path: '/api/jarvis'
      fullPath: '/api/jarvis'
      preLoaderRoute: typeof ApiJarvisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proposals/$id': {
      id: '/api/proposals/$id'
      path: '/api/proposals/$id'
      fullPath: '/api/proposals/$id'
      preLoaderRoute: typeof ApiProposalsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  CalendarRoute: CalendarRoute,
  CortexRoute: CortexRoute,
  PinRoute: PinRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiJarvisRoute: ApiJarvisRoute,
  ApiPinRoute: ApiPinRoute,
  ApiProposalsIdRoute: ApiProposalsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
