-- Seed graph: 26 leads positioned on two brain hemispheres (nx -1 left, +1 right).

INSERT OR IGNORE INTO leads (id, name, company, handle, email, channel, stage, value, score, tags, nx, ny, nz) VALUES
 ('ld-atlas','Amara Osei','Atlas Freight','@amarasei','amara@atlasfreight.io','inbound','qualified',420000,88,'["logistics","hot"]',-0.52,0.42,0.30),
 ('ld-nimbus','Devin Park','Nimbus SaaS','@devpark','devin@nimbus.so','hunter','replied',168000,74,'["saas"]',-0.60,0.22,-0.18),
 ('ld-kestrel','Riya Nair','Kestrel Dental','@riyan','riya@kestreldental.com','outbound','replied',110400,69,'["local","dental"]',-0.55,-0.05,0.42),
 ('ld-halcyon','Marcus Webb','Halcyon Fitness','@mwebb','marcus@halcyon.fit','inbound','replied',264000,81,'["fitness","multi-site"]',-0.30,0.58,-0.30),
 ('ld-orion','Sofia Reyes','Orion Realty','@sofiare','sofia@orionrealty.co','hunter','outreach_sent',92000,52,'["realty"]',-0.15,0.30,0.55),
 ('ld-vanta','Theo Lindqvist','Vanta Studio','@theol','theo@vanta.studio','inbound','won',560000,96,'["design","closed"]',-0.05,0.02,0.62),
 ('ld-quill','Jess Marin','Quill Media','@jessmarin','jess@quillmedia.tv','outbound','pending_outreach',76000,47,'["media"]',-0.38,-0.35,0.30),
 ('ld-mesa','Pablo Duarte','Mesa Tacos','@pablod','pablo@mesatacos.com','hunter','replied',84000,58,'["food","franchise"]',-0.62,-0.28,-0.12),
 ('ld-lyra','Hana Kim','Lyra Optics','@hanakim','hana@lyraoptics.com','inbound','qualified',300000,85,'["health","hot"]',-0.20,-0.52,0.18),
 ('ld-forge','Owen Blake','Forge Auto','@owenb','owen@forgeauto.co','outbound','pending_outreach',64000,41,'["auto"]',-0.44,-0.10,-0.44),
 ('ld-indigo','Priya Shah','Indigo Travel','@priyash','priya@indigotravel.com','inbound','replied',148000,71,'["travel"]',-0.10,-0.30,-0.30),
 ('ld-ridge','Cole Fischer','Ridge Roofing','@colef','cole@ridgeroofing.com','hunter','outreach_sent',136000,55,'["home-services"]',-0.34,0.12,0.02),
 ('ld-sable','Nadia Ahmad','Sable Beauty','@nadiaa','nadia@sablebeauty.com','inbound','won',176000,79,'["beauty","closed"]',-0.22,-0.55,-0.02),
 ('ld-talon','Greg Moss','Talon Security','@gregm','greg@talonsec.io','outbound','no_show',0,22,'["security","ghosted"]',0.18,0.56,0.28),
 ('ld-cinder','Lena Fischer','Cinder Coffee','@lenaf','lena@cindercoffee.co','inbound','replied',48000,63,'["hospitality"]',0.28,0.38,-0.32),
 ('ld-drift','Yusuf Ali','Drift Boards','@yusufa','yusuf@driftboards.com','hunter','outreach_sent',58000,49,'["retail"]',0.52,0.30,0.36),
 ('ld-ember','Clara Voss','Ember Yoga','@clarav','clara@emberyoga.com','inbound','qualified',96000,77,'["wellness","hot"]',0.58,0.10,-0.18),
 ('ld-pinnacle','Dan Rourke','Pinnacle Law','@danr','dan@pinnaclelaw.com','outbound','pending_outreach',312000,66,'["legal","high-value"]',0.60,-0.14,0.40),
 ('ld-haven','Mia Torres','Haven Vet','@miat','mia@havenvet.com','inbound','replied',72000,61,'["petcare"]',0.40,-0.02,0.60),
 ('ld-flux','Arjun Mehta','Flux Games','@arjunm','arjun@fluxgames.gg','hunter','replied',204000,73,'["gaming"]',0.15,-0.42,0.42),
 ('ld-grove','Ella Novak','Grove Market','@ellan','ella@grovemarket.farm','outbound','outreach_sent',44000,38,'["cpg"]',0.36,-0.50,-0.08),
 ('ld-harbor','Sam Iyer','Harbor Hotels','@sami','sam@harborhotels.com','inbound','replied',388000,84,'["hospitality","high-value"]',0.60,-0.38,-0.30),
 ('ld-iron','Kate Molloy','Iron Works Gym','@katem','kate@ironworks.gym','hunter','pending_outreach',68000,45,'["fitness"]',0.25,0.24,0.02),
 ('ld-juniper','Leo Brandt','Juniper Photos','@leob','leo@juniper.photos','inbound','won',52000,69,'["creative","closed"]',0.10,0.62,-0.10),
 ('ld-koda','Zainab Bello','Koda Events','@zainabb','zainab@kodaevents.com','outbound','no_show',0,18,'["events","ghosted"]',0.45,0.48,-0.42),
 ('ld-lumen','Noel Franks','Lumen Solar','@noelf','noel@lumensolar.energy','inbound','replied',516000,90,'["solar","high-value","hot"]',0.05,-0.20,0.20);

INSERT OR IGNORE INTO messages (id, lead_id, role, kind, body, badge, created_at) VALUES
 ('m-at-1','ld-atlas','lead','chat','We need bookings for three regional depots. Current agency keeps missing follow-ups.',NULL,unixepoch()-10200),
 ('m-at-2','ld-atlas','jarvis','automation','Pulled your intake answers. Scored 88. Prepping outreach plan for the three depots and a pricing matrix.','ACTIVE',unixepoch()-9600),
 ('m-at-3','ld-atlas','lead','chat','Can you send something before our Thursday ops review?',NULL,unixepoch()-9000),
 ('m-at-4','ld-atlas','jarvis','automation','Proposal draft is staged in Docs. Sending personalized outreach to each depot manager next.','DRAFT_READY',unixepoch()-8400),
 ('m-nb-1','ld-nimbus','jarvis','automation','Hunter scrape: matched 41 contacts at Nimbus SaaS from the public team page plus LinkedIn index.','SCRAPED',unixepoch()-14200),
 ('m-nb-2','ld-nimbus','jarvis','automation','Sent opener referencing their Series A coverage. Delivered 09:42.','SENT',unixepoch()-13800),
 ('m-nb-3','ld-nimbus','lead','chat','Timing is good. We are reworking pipeline ops this quarter. What does onboarding look like?',NULL,unixepoch()-11400),
 ('m-nb-4','ld-nimbus','jarvis','automation','Drafted reply: 10-day onboarding, two live checkpoints, async Slack line. Queued for your approval.','PENDING',unixepoch()-11000),
 ('m-ks-1','ld-kestrel','jarvis','automation','Hunter: batch 14 sweep surfaced 29 dental groups in the target band.','SCRAPED',unixepoch()-22200),
 ('m-ks-2','ld-kestrel','jarvis','automation','Outbound: intro plus one case line about recall automation for dental groups.','SENT',unixepoch()-21800),
 ('m-ks-3','ld-kestrel','lead','chat','Recall no-shows are killing us. If your system books and reminds, I want in.',NULL,unixepoch()-10800),
 ('m-ks-4','ld-kestrel','jarvis','automation','Offered the Tuesday 10:20 slot with a two-step SMS reminder chain. Awaiting her pick.','ACTIVE',unixepoch()-10200),
 ('m-hc-1','ld-halcyon','lead','chat','Inbound from the site form. Four gyms, one owner, no marketing person.',NULL,unixepoch()-9600),
 ('m-hc-2','ld-halcyon','jarvis','automation','Scored 81. Built a 4-site rollout outline and dropped it into the thread.','ACTIVE',unixepoch()-9000),
 ('m-hc-3','ld-halcyon','lead','chat','Book me a call for Friday. After 2pm.',NULL,unixepoch()-8100),
 ('m-vn-1','ld-vanta','lead','chat','Referred by Lumen. We need a partner, not another vendor.',NULL,unixepoch()-604800),
 ('m-vn-2','ld-vanta','jarvis','automation','Ran discovery asynchronously. Scored 96. Proposal and kickoff pack shipped.','WON',unixepoch()-540000),
 ('m-ms-1','ld-mesa','jarvis','automation','Hunter: 29 fit contacts across three Mesa locations. Owner direct line found.','SCRAPED',unixepoch()-30200),
 ('m-ms-2','ld-mesa','lead','chat','Send me something plain. No 40-slide deck.',NULL,unixepoch()-26400),
 ('m-ms-3','ld-mesa','jarvis','automation','Switched to the one-page format. Queued for his 8am inbox window.','PENDING',unixepoch()-25900),
 ('m-ly-1','ld-lyra','lead','chat','Want to talk next week. Budget approved.',NULL,unixepoch()-50200),
 ('m-ly-2','ld-lyra','jarvis','automation','Scored 85. Calendar link sent with three slots and a pre-read one-pager.','ACTIVE',unixepoch()-49800),
 ('m-sb-1','ld-sable','lead','chat','Need bookings automation for two studios before the holiday rush.',NULL,unixepoch()-1209600),
 ('m-sb-2','ld-sable','jarvis','automation','Proposal accepted. Kickoff scheduled. Moved to delivery.','WON',unixepoch()-1150000),
 ('m-cn-1','ld-cinder','lead','chat','We run three roasteries. Wholesale leads keep getting lost in DMs.',NULL,unixepoch()-40200),
 ('m-cn-2','ld-cinder','jarvis','automation','Mapped the wholesale intake. Suggested one pipeline for all DMs and referrals.','ACTIVE',unixepoch()-39800),
 ('m-em-1','ld-ember','lead','chat','Retreat bookings stall every September. Can you fix the follow-up drop?',NULL,unixepoch()-58200),
 ('m-em-2','ld-ember','jarvis','automation','Built a six-touch retreat sequence with weather-window timing. First send scheduled.','ACTIVE',unixepoch()-57800),
 ('m-hv-1','ld-haven','lead','chat','New client intake doubles every holiday. Staff drowns in calls.',NULL,unixepoch()-76200),
 ('m-hv-2','ld-haven','jarvis','automation','Offered voice plus SMS intake with weekly capacity caps. Awaiting her response.','PENDING',unixepoch()-75800),
 ('m-fx-1','ld-flux','jarvis','automation','Hunter: matched 33 contacts from the studio credits pages and podcast appearances.','SCRAPED',unixepoch()-86200),
 ('m-fx-2','ld-flux','lead','chat','We pitch publishers monthly. If you keep the pipeline full, keep going.',NULL,unixepoch()-80400),
 ('m-hb-1','ld-harbor','lead','chat','Group sales team quit. We are exposed for Q4 events.',NULL,unixepoch()-66200),
 ('m-hb-2','ld-harbor','jarvis','automation','Scored 84. Drafted an interim outbound engine plus inbound triage. NDA signed, pre-read staged.','ACTIVE',unixepoch()-65400),
 ('m-jn-1','ld-juniper','lead','chat','Weddings book me a year out. I need the quiet months filled.',NULL,unixepoch()-1814400),
 ('m-jn-2','ld-juniper','jarvis','automation','Built a shoulder-season corporate headshot pipeline. First invoice closed.','WON',unixepoch()-1750000),
 ('m-lm-1','ld-lumen','lead','chat','Inbound from your referral link. We did $4.2M last year, no SDR team.',NULL,unixepoch()-30600),
 ('m-lm-2','ld-lumen','jarvis','automation','Scored 90. Assembled a territory plan with 3 regional crews. Proposal in Docs.','ACTIVE',unixepoch()-30000),
 ('m-lm-3','ld-lumen','lead','chat','This is exactly the shape I wanted. Walking it into our Monday leads meeting.',NULL,unixepoch()-28800);

INSERT OR IGNORE INTO events (kind, icon, text, datum, created_at) VALUES
 ('scrape','check','Hunter sweep: 214 public profiles indexed, 41 fit','41',unixepoch()-3600),
 ('scrape','check','Cleanroom match: 29 dental groups in target band','29',unixepoch()-3480),
 ('alert','warn','Talon Security went silent after 3 sends','3',unixepoch()-3300),
 ('reply','check','Atlas Freight: reply landed, scored 88','88',unixepoch()-3120),
 ('stage','check','Harbor Hotels moved Replied to Qualified','84',unixepoch()-2940),
 ('scrape','check','Hunter: franchise signal on Mesa Tacos','HQ',unixepoch()-2760),
 ('metric','check','Pipeline value crossed $2.6M tracked','2.6M',unixepoch()-2520),
 ('alert','warn','Throttling outbound: daily cap 80 percent used','80%',unixepoch()-2340),
 ('reply','check','Lumen Solar: budget confirmed on thread','90',unixepoch()-2100),
 ('scrape','lead','New node drafted: Flux Games cluster','33',unixepoch()-1860),
 ('stage','check','Vanta Studio closed, onboarding kicked','96',unixepoch()-1680),
 ('metric','check','Reply rate up to 38.1 percent this week','38.1%',unixepoch()-1440),
 ('alert','warn','Koda Events no-show risk: two misses','2',unixepoch()-1200),
 ('scrape','check','Hunter: legal vertical sweep queued','Q',unixepoch()-960),
 ('reply','check','Ember Yoga: retreat sequence opened','77',unixepoch()-720),
 ('system','check','Nexus sync: all edge functions green','OK',unixepoch()-480);

INSERT OR IGNORE INTO settings (key, value) VALUES
 ('hunter_running','1'),
 ('outreach_running','1'),
 ('daily_send_cap','120'),
 ('auto_reply','1'),
 ('throttle_pct','72');
